[[Cubature]]
arch = "aarch64"
git-tree-sha1 = "b6b374b8c72b97ff5d528158e6695c72b17951cf"
os = "macos"

    [[Cubature.download]]
    sha256 = "deaebc892c98e5d80c5ea4c818a437861185a815145eed33893117bc852320bd"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.aarch64-apple-darwin.tar.gz"
[[Cubature]]
arch = "aarch64"
git-tree-sha1 = "3ccf624e3086cf148ba37c8a5dd012a3bdb82393"
libc = "glibc"
os = "linux"

    [[Cubature.download]]
    sha256 = "767035332dcd27d1d27665cc3dbcca4f334aa4972ef293e45b08697830f32959"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.aarch64-linux-gnu.tar.gz"
[[Cubature]]
arch = "aarch64"
git-tree-sha1 = "4efd2dd217c0c5220c99636d62136a146be4a9ad"
libc = "musl"
os = "linux"

    [[Cubature.download]]
    sha256 = "a03169c2e534b1066b92942037a68c5b9a858c8186c94233565ee6cddc84ec1f"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.aarch64-linux-musl.tar.gz"
[[Cubature]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "58013531babc1374936cf4f1cf150c43a8a7fc04"
libc = "glibc"
os = "linux"

    [[Cubature.download]]
    sha256 = "18bf4c7efed50948717c957c300e14f1904da84ebd3f3df424719e4d860ac3d6"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.armv6l-linux-gnueabihf.tar.gz"
[[Cubature]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "35a482bbf521d7774a6b93deb4664643221e7af2"
libc = "musl"
os = "linux"

    [[Cubature.download]]
    sha256 = "c8f1aa8a1db10eb1cd5734cbdc9d3becafe13a1e2cfdbefcf563416086dc7dca"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.armv6l-linux-musleabihf.tar.gz"
[[Cubature]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "546c0f5ba8cbee9609e491cd9ad96d8c83830f2d"
libc = "glibc"
os = "linux"

    [[Cubature.download]]
    sha256 = "9c3a8c6d452569cfb2b99df271104d906a2eb248b6a589f6f460d9d53295e886"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.armv7l-linux-gnueabihf.tar.gz"
[[Cubature]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f102a036a06bf85b9b9650539fc9cf67cb88f8f2"
libc = "musl"
os = "linux"

    [[Cubature.download]]
    sha256 = "e47c1e16c8a86ff8fd3950592606229bf933643335f60df82a93ae60f81d51f7"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.armv7l-linux-musleabihf.tar.gz"
[[Cubature]]
arch = "i686"
git-tree-sha1 = "a2133ddaa7cee1f365aa004bd4c52fea9f7d5989"
libc = "glibc"
os = "linux"

    [[Cubature.download]]
    sha256 = "1f9007896a1a8a8f1018468c2bd1cec6d6085c2c9172ae0e762c6fffc520e75b"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.i686-linux-gnu.tar.gz"
[[Cubature]]
arch = "i686"
git-tree-sha1 = "e7d75f29b246d1d2defaaaef14a656dda3db5240"
libc = "musl"
os = "linux"

    [[Cubature.download]]
    sha256 = "9bdc197b738c4d8b090ada44e8d86878f6f20abbac4a881fdad1d33313253e91"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.i686-linux-musl.tar.gz"
[[Cubature]]
arch = "i686"
git-tree-sha1 = "ba95dbc8d1f6618ed616a128d2a5892c3f0f9357"
os = "windows"

    [[Cubature.download]]
    sha256 = "09d4beb2869e07d807418b25a852973ce03e2f59866951da08cefa462dcac79b"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.i686-w64-mingw32.tar.gz"
[[Cubature]]
arch = "powerpc64le"
git-tree-sha1 = "d18a2c39e99cab7bb37c2760c2ca2ce75a8a56f2"
libc = "glibc"
os = "linux"

    [[Cubature.download]]
    sha256 = "2798276574f25fcb83614c951304db6c6d4068d3fc6f3486a2b00f3735067e0b"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.powerpc64le-linux-gnu.tar.gz"
[[Cubature]]
arch = "x86_64"
git-tree-sha1 = "ee34b8edd1b7a8b9dd8dbacb0773de66dd3e44d7"
os = "macos"

    [[Cubature.download]]
    sha256 = "bd0aa5a28dbb613a988807147ec61632bce2f162d67d90c361baddd72bbec13c"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.x86_64-apple-darwin.tar.gz"
[[Cubature]]
arch = "x86_64"
git-tree-sha1 = "885fff8f96f7b30c00d65b9753781642de1b37e2"
libc = "glibc"
os = "linux"

    [[Cubature.download]]
    sha256 = "b8d3ee8e44f4443b12887422fafc008991764198a289da3a006434b1684e4cfe"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.x86_64-linux-gnu.tar.gz"
[[Cubature]]
arch = "x86_64"
git-tree-sha1 = "547844259b0797d3ea84df2056fa29df58e5a606"
libc = "musl"
os = "linux"

    [[Cubature.download]]
    sha256 = "0505f57fc28281dd0c29c14e9987814e9f4a6387fef477e64662125c46c7de8a"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.x86_64-linux-musl.tar.gz"
[[Cubature]]
arch = "x86_64"
git-tree-sha1 = "c7c732c6895daeeefd7768088f4dac31359bd31a"
os = "freebsd"

    [[Cubature.download]]
    sha256 = "930983b4696d3085446c600e08eed1ca67cd76fe54a1a0e322247aff3788382e"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.x86_64-unknown-freebsd.tar.gz"
[[Cubature]]
arch = "x86_64"
git-tree-sha1 = "e2c6e3800d58729ac07e04f0c603569fc75e8fb6"
os = "windows"

    [[Cubature.download]]
    sha256 = "8f8ab59d30300d57ac0cb7b011a1ae70bf5df99aa6f305fc930b8abb4a817ac5"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.5+0/Cubature.v1.0.5.x86_64-w64-mingw32.tar.gz"
